{
 "title": "Payment Service Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "label_values(go_memstats_alloc_bytes,job)"
   },
   {
    "name": "interval",
    "query": "1s, 2s, 5s, 10s, 30s, 1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$interval])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "mem alloc" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes{job=\"$service\"}[$interval])*10",
     "legendFormat": "mem usage"
    }
   ]
  },
  {
   "title": "Go Routine",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(go_goroutines{job=\"$service\"}[$interval]))",
     "legendFormat": "go routine"
    }
   ]
  },
  {
   "title": "Go - Memstats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"payment-service\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"payment-service\"}[$interval])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"payment-service\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"payment-service\"}",
     "legendFormat": "heap inuse"
    }
   ]
  }
 ]
}